title: 'Sacha Trémoureux'
description: 'Réservoir de pensées fuyantes'
url: 'https://s.tremoureux.fr'
owner:
  name: 'Sacha Trémoureux'
  email: 'sacha@tremoureux.fr'

highlighter: pygments
baseurl: ""

sass:
    style: :compressed

markdown:    redcarpet

timezone:    Europe/Paris
future:      true

permalink:   /:categories/:title/

default_locale: fr

links:
  - title: Norvège 2012
    url: /norvege/
  - title: Github
    url: https://github.com/tsacha/
    external: true
  - title: À propos
    url: /about/    


picture:
  source: "images/"
  output: "generated"
  markup: "picture"
  presets:
    norvege:
      ppi: [1, 1.5]
      source_lrg:
        media: "(min-width: 50em)"
        width: 800
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    blog:
      ppi: [1, 1.5]
      source_lrg:
        media: "(min-width: 50em)"
        width: 800
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]