title: 'Sacha Trémoureux'
description: 'Réservoir de pensées fuyantes'

highlighter: pygments
baseurl:

sass:
    style: :compressed

markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


timezone:    Europe/Paris
future:      true

permalink:   /:categories/:title

default_locale: fr

links:
  - title: À propos
    url: /about/
  - title: Norvège 2012
    url: /norvege/
  - title: Github
    url: https://github.com/tsacha/
    external: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]